### PR TITLE
upgrading to latest request version

### PR DESCRIPTION
**Pull request by kdstew**
We were running into an error 

```
Unhandled rejection TypeError: Cannot read property 'payload' of undefined
```

when handling a caught error like below with the line `reply(Boom.notFound());`

```
show: (request, reply) => {
  Product.where('id', request.params.id).fetch({require: true})
  .then( (product) => {
    reply(product);
  })
  .catch( (err) => {
    reply(Boom.notFound());
  });
}
```

After a bit of trial and error we were able to track down the problem to a possible dependency conflict.  We pulled a copy of this repo updated the dependency for `request` and our error magically disappeared.

### CODE REVIEW

**Comment by ethanmick** [comment]
:+1: Thanks!

**Comment by pklingem** [comment]
@ethanmick could you do a patch version bump for this?

**Comment by ethanmick** [comment]
Yep, momentarily.

As an aside, are you still on Hapi < 10.0? This hasn't been updated in a while, would it help if I updated to the latest version of Hapi?

**Comment by kdstew** [comment]
Thanks @ethanmick 
We are Hapi > 11.0.  A bump to the latest hapi version would be good

**Pull request merged**
